# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f40220d8773dd9c7649541d66e0cc6640608e49f33fa6313a4f1f4b1f84e97c30af66a9becee32cec3165f58afc47020093e65014d264a5e8b91d090cbfb4e8f

test:
  secret_key_base: 7521e1fc656c54c49ea5dc65e9c1dae4ad20e9018c1a0b69c59681b16f881b2e471306a31a2b586fdc25bf0e5ec19cc588c6032e618ae6dbc9cb15b2f8b754ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
